#!/bin/sh

set -e

rm -fr \
  tor-router-gnome_1.0* \
  tor-router-gnome/debian/files \
  tor-router-gnome/debian/tor-router-gnome/ \
  tor-router-gnome/debian/tor-router-gnome.substvars \
  tor-router-gnome/debian/tor-router-gnome.debhelper.log \
  tor-router-gnome/debian/.debhelper/

exit 0
