.TH tor-router-gnome 1 "2023-10-06"

.SH NAME
tor-router-gnome \- Quickly enable and disable TOR routing system wide

.SH SYNOPSIS
.B tor-router-gnome
.br

.SH DESCRIPTION
.B tor-router-gnome
allows you to quickly enable and disable TOR routing system wide.

.SH ENVIRONMENT
Menus, labels and icons can be customized by passing the environment variables:
.br
.br
APP_ICON
.br
MENU_START
.br
MENU_STOP
.br
MENU_TORCHK
.br
MENU_RELOAD
.br
MENU_STATUS
.br
MENU_SETTINGS
.br
MENU_DONATE
.br
MENU_ABOUT
.br
MENU_EXIT
.br
LABEL_OFFLINE
.br
LABEL_STOPPED
.br
LABEL_DISABLED
.br
LABEL_ENABLED
.br
ICON_OFFLINE
.br
ICON_STOPPED
.br
ICON_DISABLED
.br
ICON_ENABLED
.br
ICON_DONATE
